- include/riakc.hrl
- rebar.config
- src/riakc_pb_socket.erl
**Note**: **Bors will fail** on this until a new version is referenced in rebar.config incorporating the update in basho/riak_pb#105 and the riak_core update is reviewed/merged.
Part of [RIAK-1481](https://bashoeng.atlassian.net/browse/RIAK-1481).
The active preflist will return primary/fallback partitions and nodes for the available nodes at the time of query. Primary/fallback will be annotated.
This involves updates to our RiakKV WB code, RiakPB, Riak-Erlang-Http-Client, Riak-Erlang-Client.
*The impetus for adding this to the API started with a mailing list question answered by Charlie Voiselle, http://lists.basho.com/pipermail/riak-users_lists.basho.com/2015-January/016527.html, which involved a snippet of code that we've given clients multiple times. This was then discussed with …
> add get_preflist to erlang-client

- rebar.config
- src/riakc_pb_socket.erl
Related to RIAK-1547 (#402)... in order for the erlang-client to allow for a user-given timeout (or default) for synchronously creating a search index. Relies on https://github.com/basho/riak_pb/pull/112.
> update erlang-client to have sync-create put timeout

- src/riakc_pb_socket.erl
Currently, enabling auto_reconnect only works if the server is up when the client starts.
If the first connect fails, riakc_pb_socket:start_link will return {:ok, pid} but will never auto reconnect.
> Ensure auto_reconnect if first connect fails

- src/riakc_ts.erl
RTS-480.
Depends on https://github.com/basho/riak_kv/pull/1243 and https://github.com/basho/riak_pb/pull/146.
> riak_ts:get now returns {ColumnDescriptions, Rows}

- src/riakc_ts.erl
Note: For the description of `get/4` to be accurate, https://github.com/basho/riak_kv/pull/1243 and https://github.com/basho/riak-erlang-client/pull/242 need to go first.
> Add docstrings for all riakc_ts external API functions

- .gitignore
- src/riakc_pb_socket.erl
- src/riakc_ts.erl
- src/riakc_ts_put_operator.erl
- src/riakc_ts_query_operator.erl
Use different versions of riak_pb_ts_codec:encode_xxxxx since the originals changed. 
Also fixed some specs here and there. 
This depends on basho/riak_pb#164
> Fix issues from riak_pb timestamp encoding changes.

- src/riakc_pb_socket.erl
- src/riakc_ts.erl
RTS-697. Depends on https://github.com/basho/riak_kv/pull/1291.
This PR introduces `riakc_ts:stream_list_keys/3` and scraps `riakc_ts:list_keys/3`.
> use streaming list_keys for TS

- rebar.config
- src/riakc_pb_socket.erl
- src/riakc_ts.erl
- src/riakc_ts_put_operator.erl
This is one of three related PRs (basho/riak_kv#1323 is the corresponding PR for riak_kv, basho/riak_pb#176 is the corresponding one for riak_pb), to streamline put requests using TTB encoding instead of PB.
As with the current end-to-end/timeseries branch, the TTB encoded messages are still handled by the riak_kv_pb service; even though they are not PB-encoded messages, they reuse the erlang infrastructure around generating erlang messages from the .proto definitions.
Changes include:
1) riakc_ts.erl put operator has been modified to lookup encoding method in the process dict and pass this as an argument to serialization and encoding methods.  Additional server_call method has been added to propagate this to riakc_pb_socket where the encoding is done
2) added handle_call methods to …
> Perf/ttb newmsg ts1.0 release candidate v2

- .gitignore
- rebar.config
- src/riakc_pb_socket.erl
- src/riakc_ts.erl
- src/riakc_ts_put_operator.erl
- src/riakc_ts_query_operator.erl
Ensure tsputreq and tsqueryreq are encoded / decoded as TTB. Remove switching to / from native encoding.
> READY: TS Put / Query use TTB encoding.

- .gitignore
- rebar.config
- src/riakc_pb_socket.erl
- src/riakc_ts.erl
- src/riakc_ts_put_operator.erl
- src/riakc_ts_query_operator.erl
<hr>
**Context**
This is part of a set of related PRs to rework handling of PB vs TTB encoding for client/server messages:
* https://github.com/basho/riak-erlang-client/pull/267 
* https://github.com/basho/riak_pb/pull/182
* https://github.com/basho/riak_api/pull/109
* https://github.com/basho/riak_kv/pull/1378
The original addition of alternate encodings was a hybrid implementation which 1) required the client and server to agree via a handshaking protocol about what encoding would be used, 2) used messages for both encodings that were generated from the .proto files, but some were only used for TTB encoding, and 3) allowed the server to send PB-encoded responses to TTB-encoded requests.
This work is an attempt to rationalize this situation, and to simplify how differently-encoded …
> READY: Perf/query ttb encoding

- src/riakc_ts.erl
This PR:
* unbreaks some tests (ts_simple_aggregation and possibly others) which call riakc_ts functions with `Table` argument given as a string (not binary);
* introduces guards to parameters in all functions;
* cleans up docstrings.
> sanitize args for riakc_ts functions, allow strings for Table

- src/riakc_ts.erl
- src/riakc_ts_get_operator.erl
- src/riakc_ts_query_operator.erl
This is consistent with the `tsqueryresp` case, too.
> Standardize the success response from tsgetresp and tsqueryresp

- src/riakc_ts.erl
Relates to https://github.com/basho/riak_kv/pull/1382, requires https://github.com/basho/riak_pb/pull/190.
Contains a fix for the case of `riakc_ts:get` returning an empty set, where the client connection is broken with an error message implicating 'tsgetresp'.
Also, properly decode the error message of `get_coverage` (previously, this was done in riak_kv_ts_svc, which is not the right place for assembling `#ts...` records since this module now serves PB as well as TTB messages).
> Fixup az post ttb and develop merge

- README.md
- src/riakc_pb_socket.erl
@sata ping
Fixes #287 
* Modify test to test that returned object from Riak is actually a binary
> READY: Correctly process Riak generated keys

- include/riakc.hrl
- src/riakc_pb_socket.erl
Fix for issue https://github.com/basho/riak-erlang-client/issues/199 by introducing bucket_type and bucket_and_type types, to avoid dialyzer warnings when calling fetch_type and update_type with bucket and type tuple
> Introduce bucket_type and bucket_and_type types to avoid dialyzer warnings

- src/riakc_pb_socket.erl
> Strip 'create' option from riakc_pb_socket:modify_type

- include/riakc.hrl
Include bucket type and clarify key-data.
Refs:
- https://github.com/basho/riak_kv/blob/edce9a29ed31a6877c8a861ceea0fcb6d7d8832a/src/riak_kv_mapred_term.erl#L45
- https://github.com/basho/basho_docs/blob/de152b49e29fdf3845c5a54171aa8f665cf0367d/content/riak/kv/2.1.4/developing/app-guide/advanced-mapreduce.md#inputs
> Detail mapreduce inputs type

- src/riakc_ts.erl
Required by https://github.com/basho/riak_test/pull/1213 (and eventually by https://github.com/basho/riak_kv/pull/1549). Depends on https://github.com/basho/riak_pb/pull/212.
That flag did not pass the scrutiny of three-strong panel of reviewers.
> drop the disused allow_qbuf_reuse flag

- src/riakc_pb_socket.erl
- src/riakc_ts.erl
- src/riakc_utils.erl
- test/riakc_pb_socket_tests.erl
- test/riakc_ts_tests.erl
Add code to return error when listing objects unless the `allow_listing` option is true.
Fixes #345 (CLIENTS-1067) (CLIENTS-1067) (CLIENTS-1067) and [`CLIENTS-1067`](https://bashoeng.atlassian.net/browse/CLIENTS-1067)
> Implement errors for listing operations.

- src/riakc_pb_socket.erl
- test/riakc_pb_socket_tests.erl
I noticed no Dialyzer warnings less or more with this change.
I did not run the test locally - relying on bot to do that.
> Expose CRDT update without key delegating key generation to Riak

- src/riakc_pb_socket.erl
- test/riakc_pb_socket_tests.erl
Expose CRDT update without key delegating key generation to Riak
Optional key in request and Riak-generated key are [documented
already](https://github.com/basho/basho_docs/blob/814125935ca55a5801764dcb780534a89b599dec/content/riak/kv/2.2.0/developing/api/protocol-buffers/dt-store.md#optional-parameters).
PB encoder [already has type
spec](https://github.com/basho/riak_pb/blob/4198223ec788401da5cbf2868e3181b6b5db289a/src/riak_pb_dt_codec.erl#L490-L494)
catering for optional key.
> Port PR 351 to release-2.5.3
